CREATE TABLE EMPLOYEE(
ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
JOINING_DATE DATE NOT NULL,
SALARY DOUBLE NOT NULL,
SSN VARCHAR(30) NOT NULL UNIQUE);

CREATE TABLE PERSON(
	IRSID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	FBID BIGINT,
	MEMBERTYPEID INT, 
	FIRSTNAME VARCHAR(255),
	LASTNAME VARCHAR(255),
	USERNAME VARCHAR(255),
	USERPASSWORD VARCHAR(255), 
	PICTUREURL VARCHAR(512), 
	PICTUREHEIGHT INT, 
	PICTUREWIDTH INT);

CREATE TABLE RSUser (
  rsid BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  fbid BIGINT,
  member_type_id INT, 
  user_name varchar(128) NOT NULL,
  user_email varchar(128) DEFAULT NULL,
  user_password varchar(128) DEFAULT NULL,
  nickname varchar(128) DEFAULT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  picture_url VARCHAR(512), 
  picture_height INT, 
  picture_width INT
) ;

CREATE TABLE RSUsersFriend  (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  rsuser_rsid BIGINT DEFAULT NULL,
  friend_rsid BIGINT NOT NULL,
) ;


SET SCHEMA PUBLIC
INSERT INTO PERSON VALUES(1,10152592364000261, 0,'Peter','Sagan','peter_sagan','password_pe',NULL,0,0)
INSERT INTO PERSON VALUES(2,10152592364000262, 0, 'Nasta','Kuzminova','nasta_kuzminova','password_na',NULL,0,0)
INSERT INTO PERSON VALUES(3,10152592364000264, 0, 'Leon','Tseng','leon_tseng','password_leon','https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/v/t1.0-1/c30.30.372.372/s100x100/30100_396814935263_6005583_n.jpg?oh=6660611ef721446582adae2d00d78cdd&oe=55559D0E&__gda__=1433154628_cbab996829b361ea36a101eeb9e099cd',100,100)

INSERT INTO Employee VALUES(1,'Jason1','2010-01-01',101000,'ssn1');
INSERT INTO Employee VALUES(2,'Jason2','2010-02-02',102000,'ssn2');

INSERT INTO RSUser(fbid, member_type_id, user_name, user_email, user_password, nickname, first_name, 
last_name,picture_url, picture_height, picture_width) VALUES(1001,0,'jason_chuang','jason@hihi.com',
'jason_password','jasontgi','Jason','Chuang',null,0,0);
INSERT INTO RSUser(fbid, member_type_id, user_name, user_email, user_password, nickname, first_name, 
last_name,picture_url, picture_height, picture_width) VALUES(1002,0,'bart_lee','bart@hihi.com',
'bart_password','bart','Bart','Lee',null,0,0);
INSERT INTO RSUser(fbid, member_type_id, user_name, user_email, user_password, nickname, first_name, 
last_name,picture_url, picture_height, picture_width) VALUES(10152592364000264,0,'leson_tseng','lesontseng@gmail.com',
'leon_password','leon','Leon','Tseng',
'https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/v/t1.0-1/c30.30.372.372/s100x100/30100_396814935263_6005583_n.jpg?oh=6660611ef721446582adae2d00d78cdd&oe=55559D0E&__gda__=1433154628_cbab996829b361ea36a101eeb9e099cd',
100,100);
