CREATE TABLE `Employee` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `joining_date` date NOT NULL,
  `salary` double NOT NULL,
  `ssn` varchar(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ssn` (`ssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO Employee(name, joining_date, salary, ssn) VALUES('Jason1','2010-01-01',101000,'ssn1');

CREATE TABLE IF NOT EXISTS `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nickname` varchar(128) DEFAULT NULL,
  `user_name` varchar(128) NOT NULL,
  `user_email` varchar(128) DEFAULT NULL,
  `user_password` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE Person(
  irsid BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  fbid BIGINT,
  memberTypeid INT, 
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  username VARCHAR(255),
  userpassword VARCHAR(255), 
  pictureUrl VARCHAR(512), 
  PictureWidth INT, 
  PictureHeight INT)


INSERT INTO Person VALUES(1,10152592364000261, 0,'Peter','Sagan','peter_sagan','password_pe',NULL,0,0)
INSERT INTO Person VALUES(2,10152592364000262, 0, 'Nasta','Kuzminova','nasta_kuzminova','password_na',NULL,0,0)
INSERT INTO Person VALUES(3,10152592364000264, 0, 'Leon','Tseng','leon_tseng','password_leon','https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/v/t1.0-1/c30.30.372.372/s100x100/30100_396814935263_6005583_n.jpg?oh=6660611ef721446582adae2d00d78cdd&oe=55559D0E&__gda__=1433154628_cbab996829b361ea36a101eeb9e099cd',100,100)
